#!/bin/sh
# kFreeBSD do not accept scripts as interpreters, using #!/bin/sh and sourcing.
if [ true != "$INIT_D_SCRIPT_SOURCED" ] ; then
    set "$0" "$@"; INIT_D_SCRIPT_SOURCED=true . /lib/init/init-d-script
fi
### BEGIN INIT INFO
# Provides:          snifferd
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Sniffer daemon.
# Description:       Simple sniffer.
### END INIT INFO

# Author: Andrew Gomenyuk <paltinium9889@gmail.com>

DESC="Simple sniffer"
DAEMON=/sbin/snifferd

do_start()
{
	snifferctl start
}

do_stop()
{
	snifferctl stop
	rm /tmp/.sniffer4836.pid
}

do_restart()
{
	killall snifferd
	rm /tmp/.sniffer4836.pid
	snifferctl start
}

case "$1" in
	start)
		do_start
	;;
	stop)
		do_stop
	;;
	restart)
		do_restart
	;;
	*)
		snifferctl --usage
		exit 1
	;;
esac
